// <auto-generated />
namespace Entities.Contracts
{
    using System;
    using System.Collections.Generic;

    using Entities.Models;

    /// <summary>
    /// AccountRepository interface
    /// </summary>
    public interface IAccountRepository
    {
        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="ownerId"></param>
        /// <returns></returns>
        IEnumerable<Account> AccountsByOwner(Guid ownerId);
    }
}
