// <auto-generated />
namespace Entities.Contracts
{
    /// <summary>
    /// Logger interface
    /// </summary>
    public interface ILoggerManager
    {
        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="message"></param>
        void LogInfo(string message);

        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="message"></param>
        void LogWarn(string message);

        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="message"></param>
        void LogDebug(string message);

        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="message"></param>
        void LogError(string message);
    }
}
