// <auto-generated />
namespace Entities.Contracts
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Entities.Models;

    /// <summary>
    /// OwnerRepository interface
    /// </summary>
    public interface IOwnerRepository : IRepositoryBase<Owner>
    {
        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="ownerParameters"></param>
        /// <returns></returns>
        Task<IEnumerable<Owner>> GetOwners(OwnerParameters ownerParameters, bool isCacheIgnored = false);

        /// <summary>
        /// Method contract
        /// </summary>
        /// <returns></returns>
        Task<IEnumerable<Owner>> GetAllOwnersAsync();

        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="ownerId"></param>
        /// <returns></returns>
        Task<Owner> GetOwnerByIdAsync(Guid ownerId);

        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="ownerId"></param>
        /// <returns></returns>
        Task<Owner> GetOwnerWithDetailsAsync(Guid ownerId);

        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="owner"></param>
        void CreateOwner(Owner owner);

        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="owner"></param>
        void UpdateOwner(Owner owner);

        /// <summary>
        /// Method contract
        /// </summary>
        /// <param name="owner"></param>
        void DeleteOwner(Owner owner);
    }
}
