// <auto-generated />
namespace Entities.Contracts
{
    using System.Threading.Tasks;

    /// <summary>
    /// UoF interface
    /// </summary>
    public interface IUnitOfWork
    {
        /// <summary>
        /// Method contract
        /// </summary>
        IOwnerRepository Owner { get; }

        /// <summary>
        /// Method contract
        /// </summary>
        IAccountRepository Account { get; }

        /// <summary>
        /// Method contract
        /// </summary>
        /// <returns></returns>
        Task SaveAsync();
    }
}
