// <auto-generated />
namespace Repository.Layer
{
    using System;
    using System.Linq;
    using System.Linq.Expressions;

    using Entities.Contracts;
    using Entities.DbContext;

    using Microsoft.EntityFrameworkCore;

    /// <summary>
    /// RepositoryBase generic class
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public abstract class RepositoryBase<T> : IRepositoryBase<T> where T : class
    {
        /// <summary>
        /// RepositoryContext property
        /// </summary>
        protected RepositoryContext RepositoryContext { get; set; }

        /// <summary>
        /// RepositoryBase constructor method
        /// </summary>
        /// <param name="repositoryContext"></param>
        public RepositoryBase(RepositoryContext repositoryContext)
        {
            this.RepositoryContext = repositoryContext;
        }

        /// <summary>
        /// FindAll method
        /// </summary>
        /// <returns></returns>
        public IQueryable<T> FindAll()
        {
            return this.RepositoryContext.Set<T>().AsNoTracking();
        }

        /// <summary>
        /// FindByCondition method
        /// </summary>
        /// <param name="expression"></param>
        /// <returns></returns>
        public IQueryable<T> FindByCondition(Expression<Func<T, bool>> expression)
        {
            return this.RepositoryContext.Set<T>().Where(expression).AsNoTracking();
        }

        /// <summary>
        /// Create method
        /// </summary>
        /// <param name="entity"></param>
        public void Create(T entity)
        {
            this.RepositoryContext.Set<T>().Add(entity);
        }

        /// <summary>
        /// Update method
        /// </summary>
        /// <param name="entity"></param>
        public void Update(T entity)
        {
            this.RepositoryContext.Set<T>().Update(entity);
        }

        /// <summary>
        /// Delete method
        /// </summary>
        /// <param name="entity"></param>
        public void Delete(T entity)
        {
            this.RepositoryContext.Set<T>().Remove(entity);
        }
    }
}
