// <auto-generated />
namespace AccountOwnerServer.AutoMapperProfiles
{
    using AutoMapper;

    using Entities.DTOs;
    using Entities.Models;

    /// <summary>
    /// Represent a profile class
    /// </summary>
    public class MappingProfile : Profile
    {
        /// <summary>
        /// A profile class constructor
        /// </summary>
        public MappingProfile()
        {
            CreateMap<Owner, OwnerDto>();
            CreateMap<Account, AccountDto>();
            CreateMap<OwnerForCreationDto, Owner>();
            CreateMap<OwnerForUpdateDto, Owner>();
        }
    }
}
