// <auto-generated />
namespace Entities.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// ErrorDetails class
    /// </summary>
    public class ErrorDetails
    {
        /// <summary>
        /// StatusCode property
        /// </summary>
        public int StatusCode { get; set; }

        /// <summary>
        /// Message property
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Override ToString method
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
