// <auto-generated />
namespace Entities.Models
{
    /// <summary>
    /// OwnerParameters class
    /// </summary>
    public class OwnerParameters
    {
        const int maxPageSize = 50;

        /// <summary>
        /// PageNumber property
        /// </summary>
        public int PageNumber { get; set; } = 1;

        private int _pageSize = 10;

        /// <summary>
        /// PageSize property
        /// </summary>
        public int PageSize
        {
            get
            {
                return _pageSize;
            }
            set
            {
                _pageSize = (value > maxPageSize) ? maxPageSize : value;
            }
        }
    }
}
