// <auto-generated />
namespace Entities.DbContext
{
    using Entities.Models;

    using Microsoft.EntityFrameworkCore;

    /// <summary>
    /// A context class
    /// </summary>
    public class RepositoryContext : DbContext
    {
        /// <summary>
        /// RepositoryContext constructor
        /// </summary>
        /// <param name="options"></param>
        public RepositoryContext(DbContextOptions options)
            : base(options)
        {
        }

        /// <summary>
        /// Owners property 
        /// </summary>
        public DbSet<Owner> Owners { get; set; }

        /// <summary>
        /// Accounts property
        /// </summary>
        public DbSet<Account> Accounts { get; set; }
    }
}
