// <auto-generated />
namespace Contracts
{
    using System.Threading.Tasks;

    public interface IUnitOfWork
    {
        IOwnerRepository Owner { get; }

        IAccountRepository Account { get; }

        Task SaveAsync();
    }
}
